-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.author
(
    id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    bio character varying,
    email character varying(100),
    blog_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.blog
(
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying,
    author_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comment
(
    id integer NOT NULL,
    comment character varying,
    author_id integer,
    post_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.post
(
    id integer NOT NULL,
    title character varying(200) NOT NULL,
    content character varying,
    status character varying(10),
    author_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.post_tag
(
    post_id smallint NOT NULL,
    tag_id smallint NOT NULL,
    PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.tag
(
    id integer NOT NULL,
    tag_name character varying(20),
    blog_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE public.author
    ADD FOREIGN KEY (blog_id)
    REFERENCES public.blog (id)
    NOT VALID;


ALTER TABLE public.blog
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id)
    NOT VALID;


ALTER TABLE public.comment
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id)
    NOT VALID;


ALTER TABLE public.comment
    ADD FOREIGN KEY (post_id)
    REFERENCES public.post (id)
    NOT VALID;


ALTER TABLE public.post
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id)
    NOT VALID;


ALTER TABLE public.post_tag
    ADD FOREIGN KEY (post_id)
    REFERENCES public.post (id)
    NOT VALID;


ALTER TABLE public.post_tag
    ADD FOREIGN KEY (tag_id)
    REFERENCES public.tag (id)
    NOT VALID;


ALTER TABLE public.tag
    ADD FOREIGN KEY (blog_id)
    REFERENCES public.blog (id)
    NOT VALID;

END;